name: Create Database from production Dump and Apply Migrations

on:
  push:
    branches:
      - main

jobs:
  create-db-and-migrate:
    runs-on: ubuntu-latest

    services:
        postgres:
          image: postgres:12
          env:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 12345
            POSTGRES_DB: Inventory
            POSTGRES_HOST: localhost
            POSTGRES_PORT: 5432
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
          ports:     
            - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main  # Checkout the production branch
  
      - name: Create  Database
        env:
          PGPASSWORD: 12345
        run: |        
          createdb -h localhost -U postgres temp_db
  
      - name: Restore Production Backup to Template Database
        env:
          PGPASSWORD: 12345  
        run: |          
            pg_restore -h localhost -U postgres -d temp_db < ./testdump.dump
  
      - name: Install Golang Migrate
        run: |
            go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

      - name: Add Go Bin Directory to PATH
        run: |
          echo "$HOME/go/bin" >> $GITHUB_PATH  # Add the directory where Go installs binaries to the PATH

              
      - name: Run Migrations
        env:
          PGPASSWORD: 12345
        run: |         
          migrate -database "postgres://postgres@127.0.0.1:5432/temp_db?sslmode=disable" -path ./db/migrations up
    