name: Create Database from Artifact Dump and Apply Migrations

on:
  push:
    branches:
      - main

jobs:
  create-db-and-migrate:
    runs-on: ubuntu-latest

    services:
        postgres:
          image: postgres:12
          env:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 12345
            POSTGRES_DB: Inventory
            POSTGRES_HOST: localhost
            POSTGRES_PORT: 5432
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
          ports:     
            - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

     
      - name: Generate Database Dump
        env:
          PGPASSWORD: 12345
        run: |
          # Generate the database dump
          pg_dump -h localhost -U postgres  -d Inventory -f mydb_dump.sql

      - name: Save Database Dump as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: db-dump
          path: mydb_dump.sql


      - name: Create New Database
        env:
            PGPASSWORD: 12345
        run: |
          # Create a new database
          psql -h localhost -U postgres -c "CREATE DATABASE newdb;"

      - name: Download Database Dump Artifact
        uses: actions/download-artifact@v2
        with:
          name: db-dump
          path: dump/

      - name: Restore Dump to New Database
        env:
            PGPASSWORD: 12345
        run: |
          # Restore the dump to the newly created database
          psql -h localhost -U postgres -d newdb -f dump/mydb_dump.sql

      - name: Install Golang Migrate
        run: |
            go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest
  


      - name: Run Migrations
        env:
          PGPASSWORD: 12345
        run: |         
          migrate -database "postgres://postgres@127.0.0.1:5432/newdb?sslmode=disable" -path ./db/migrations up
    