name: Migrate PostgreSQL Database

on:
  push:
    branches:
      - main  # Change this to your desired branch

jobs:
  migrate_db:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 12345
          POSTGRES_DB: Inventory
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18  

      - name: Install Golang Migrate
        run: |
          go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

      - name: Set Database as Template
        env:
         PGPASSWORD: 12345
        run: |
          psql -h 127.0.0.1 -p 5432 -U postgres -d Inventory -w -c "UPDATE pg_database SET datistemplate = true WHERE datname = 'Inventory';"

      - name: Create Temporary Database
        env:
          PGPASSWORD: 12345
        run: |
          # Create a temporary database using the template option        
          psql -h 127.0.0.1 -p 5432 -U postgres  -d Inventory -w -c "CREATE DATABASE temp_inventory OWNER postgres TEMPLATE 'Inventory';"


      - name: Get Current DB Version
        id: get_db_version
        run: |
          current_version=$(migrate -database "postgres://postgres@127.0.0.1:5432/temp_inventory?sslmode=disable" -path ./db/migrations version)
          echo "::set-output name=current_version::$current_version"

      - name: Run Migrations
        run: |
          current_version="${{ steps.get_db_version.outputs.current_version }}"
          migrate -database "postgres://postgres@127.0.0.1:5432/temp_inventory?sslmode=disable" -path ./db/migrations goto "$current_version"
          migrate -database "postgres://postgres@127.0.0.1:5432/temp_inventory?sslmode=disable" -path ./db/migrations up

          

