name: Migrate PostgreSQL Database

on:
  push:
    branches:
      - main  # Change this to your desired branch

jobs:
  migrate_db:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18  

      - name: Install Golang Migrate
        run: |
          go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest


      - name: Create Temporary Database
        env:
          PGPASSWORD: 12345
        run: |

          psql -h 127.0.0.1 -p 5432 -U postgres  -d Inventorynew -w -c "CREATE DATABASE temp_inventory OWNER postgres TEMPLATE 'Inventorynew';"


      - name: Run Migrations
        env:
         PGPASSWORD: 12345
        run: |         
          migrate -database "postgres://postgres@127.0.0.1:5432/temp_inventory?sslmode=disable" -path ./db/migrations up


   
     

