name: Migrate Go package

on: [push]

jobs:
  migrate:

    runs-on: ubuntu-latest
    env:
      PGHOST: localhost
      PGPORT: 5432
      PGUSER: onito_inv_user
      PGPASSWORD: abcd
      PGDATABASE: Inventory
    steps:
      - uses: actions/checkout@v3
  
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18
 
      - name: Set up PostgreSQL client
        run: sudo apt-get install postgresql-client

      - name: Postgres Dump Backup
        uses: tj-actions/pg-dump@v2.3
        with:
          database_url: "postgres://onito_inv_user:abcd@localhost:5432/Inventory"
          path: "backups/backup.sql" 
          options: "-O"  
          


              